main: me.zombie_striker.lobbyapi.Main
version: ${project.version}
api-version: 1.17
name: LobbyAPI
commands:
  Lobby:
    description: Opens the world menu
    aliases: [hub]
  LobbyAPI:
    description: Get access to all lobbyAPI commands
permissions:
  lobbyapi.*:
    description: Gives access to all LobbyAPI features
    children:
      lobbyapi.commands: true
      lobbyapi.user: true
      lobbyapi.bypassworldlimits: true
  lobbyapi.user:
    default: true
    description: Gives access that only a user should have, which is to access the hub command
    children:
      lobbyapi.hub: true
depend: [PluginConstructorAPI]
softdepend: [MultiverseCore]
load: POSTWORLD
authors: [Zombie_Striker, dmblc]